---
title: "Data_Wrangling"
author: "Jaclyn Verity"
date: "9/18/18"
output: github_document
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Import FAS csv files

Import my first csv

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
names(litters_data)
```

## Import FAS pups csv files

Import Learning Assessment

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
names(pups_data)
```

## Other Formats

Excel.

```{r}
mlb_data = readxl::read_excel(path = "./data/mlb11.xlsx")
mlb_subdata = readxl::read_excel(path = "./data/mlb11.xlsx",
                              range = "A1:E17")
```

SAS data set.

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat")
```

## Compare with base R

```{r}
pups_readr = read_csv("./data/FAS_pups.csv")
pups_baser = read.csv("./data/FAS_pups.csv")

pups_readr
pups_baser
```

Readr only prints first 10 rows, it wont guess at what you mean. Base R will cause you errors. Small difference that make a big difference in big data workflows. 